---
- hosts: 172.31.25.126
  become: yes
  tasks:
  - name: i want to excute command
    command: hostname -f
    register: myresult
   
  - name: i want display result
    debug:
     msg: "{{myresult}}"