---
- hosts: 172.31.25.126
  become: yes
  tasks:
  - name: i want install command
      command: hostname -f
      register: myresult
   
   - name: iwant display result
     debug:
       msg: "{{myresult}}"