---
- hosts: 172.31.25.126
  become: yes
  tasks:
  - name: i want create a myfile
    file:
     path: /home/ubuntu/myfile
     state: touch
  - name: i want install apache2
    apt:
     name: apache2
     state: present
  - name: i want to copy the textfile
    copy:
     src: mytestfile
     dest: /var/www/html/index.html
  - name: i want create dynamic file
    template:
      src: mydynamicfile.j2
      dest: /var/www/html/index.html
