---
- hosts: 172.31.25.126
  become: yes
  tasks:
  - name: i want create a myfile
    file:
     path: /home/ubuntu/myfile
     state: touch
  - name: i want install apache2
    apt:
     name: apache2
     state: present
    notify: startmywebser
  - name: i want to copy the textfile
    copy:
     src: mytestfile
     dest: /var/www/html/index.html
  - name: i want create dynamic file
    template:
      src: mydynamicfile.j2
      dest: /var/www/html/index.html
    notify: startmywebser
  
  - name: i want to download the file
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.0/bin/apache-tomcat-10.0.0.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.0.tar.gz
      force_basic_auth: yes
  
  handlers:
  - name: startmywebser
    service:
      name: apache2
      state: restarted