---
- hosts: 172.31.25.126
  become: yes
  tasks:
  - name: iwant to wget
    apt:
     name: wget
     state: present
    tags: mywget
  
  - name: i want to install git
    apt:
     name: git
     state: present
    tags: mygit

  - name: i want to install tree
    apt:
     name: tree
     state: present
    tags: mytree

