---
- name: Configure OSPF routing
  hosts: all
  become: true

  vars:
    ospf_process_id: 1
    ospf_networks:
      - network: 172.31.16.0/28
        area: 0
      - network: 172.31.32.0/28
        area: 0
      - network: 172.31.48.0/28
        area: 0

  tasks:
    - name: Install ospfd
      apt:
        name: quagga
        state: present

    - name: Configure OSPF
      template:
        src: ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf
      notify: Restart OSPF

    - name: Configure interface IP addresses
      interface:
        name: "{{ item.interface }}"
        ip_address: "{{ item.ip_address }}"
        state: present
      with_items:
        - { interface: eth0, ip_address: "172.31.16.1/28" }
        - { interface: eth1, ip_address: "172.31.32.1/28" }
        - { interface: eth2, ip_address: "172.31.48.1/28" }

  handlers:
    - name: Restart OSPF
      service:
        name: ospfd
        state: restarted