---
# tasks file for mywebprodrole
- include_tasks: adduser.yml
- include_tasks: installjava.yml
- include_tasks: downlod.yml
- include_tasks: permission.yml
- include_tasks: dashboard.yml
- include_tasks: starttomcat.yml